name: telebirr_flutter_elements
description: Optional Flutter UI components for the Telebirr payment SDK
version: 1.0.0
homepage: https://github.com/7Doyo/telebirr-sdk
repository: https://github.com/7Doyo/telebirr-sdk
issue_tracker: https://github.com/7Doyo/telebirr-sdk/issues
generate: true
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # intl: any
  telebirr_sdk_core: ^1.0.0
    # path: ../dart_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
