name: telebirr_sdk_core
description: Headless Dart SDK for Ethio Telecom Telebirr payment gateway
version: 1.0.0
homepage: https://github.com/7Doyo/telebirr-sdk
repository: https://github.com/7Doyo/telebirr-sdk
issue_tracker: https://github.com/7Doyo/telebirr-sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cryptography: ^2.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
